### ISSUE TITLE
Move login form from Django to Angular

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#689]
__Description:__

Move login form from Django to Angular

It contains spliting login and register to separate views (register form will be moved to separate view in #686). 

__Current behaviour:__

Login and register is handled by Django.

__Expected behaviour:__

Describe expected behaviour of application.

__Steps to reproduce:__

Register stays in Django (or is alread moved as described in #686), login is served by Angular.

**Comment by magul** [comment]
@weronikafelczak

**Comment by radoslawroszkowiak** [comment]
@magul, just asking, how do you imagine the implentation of this ticket?

The fact that the app was split into server-rendered Django views and ng views made things a bit complicated.

If you decide to have this view in angular NOW, it will have to rely on Django session cookies to be able to "share" authentication between ng / django, isn't it?

But, ultimately, this app will be all moved to ng and there will only be the REST API in Django. I don't think you'll want to keep session / cookies in the stateless API, but you'd rather used some sort of tokens instead.

The issue is caused mostly by the fact that current HTTP API calls in the app are very tighly coupled with the authentication method (see `withCredentials` everywhere) as far as I can see.


I think the first step, before touching this ticket, is to:

1. Subclass default HTTP service (Angular <=4.2) or create HTTP interceptor (Angular 4.3+) that will handle your authentication logic (like adding headers or whatever else) and use it everywhere in the components / services instead of "plain" angular's HTTP service. If you decide to go with cookies in this very ticket, it will be easier to switch later on.
2. Make authentication service more of a blackbox for the components - they should not know and care about any cookies / sessions / whatever related to authentication.

**Comment by radoslawroszkowiak** [comment]
Done by @weronikafelczak
